# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for Extras folder

on:
  push:
    paths:
      - .github/workflows/mvn-extras.yaml
      - extras/**
  pull_request:
    paths:
      - .github/workflows/mvn-extras.yaml
      - extras/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: |
          git config --system core.longpaths true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-extras-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-quick-examples pam-vagrant

      - name: Build offliner-maven-plugin
        run: |
          pushd extras/offliner-maven-plugin
          mvn -B clean package --no-transfer-progress
          popd
    
      - name: Build extras/bdd-ui/maven-java-bdd-demo
        run: |
          pushd extras/bdd-ui/maven-java-bdd-demo
          mvn -B clean package --no-transfer-progress
          popd

      # Jave 11 Builds
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build extras/task-automator
        run: |
          pushd extras/task-automator
          mvn -B clean package --no-transfer-progress
          popd
      
      - name: Build extras/data-generator
        run: |
          pushd extras/data-generator
          mvn -B clean package --no-transfer-progress
          popd

      # NPM Builds
      - name: Setup node Build bdd-ui
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build extras/bdd-ui/feature-file-helper-front-end
        run: |
          pushd extras/bdd-ui/feature-file-helper-front-end
          npm install -g @angular/cli
          npm install
          ng build
          popd

      - name: Build extras/bdd-ui/feature-file-helper-back-end
        run: |
          pushd extras/bdd-ui/feature-file-helper-back-end
          npm install
          popd
